# Generated by Django 2.1.7 on 2019-02-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuari', models.TextField(blank=True, null=True)),
                ('ProducteCompra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarritoDeCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProducteId', models.IntegerField()),
                ('Prize', models.FloatField()),
                ('Discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cataleg',
            fields=[
                ('ProducteId', models.IntegerField(primary_key=True, serialize=False)),
                ('Photo', models.ImageField(upload_to='photos/')),
                ('Descripcio_prod', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProducteId', models.IntegerField()),
                ('Producte', models.TextField()),
                ('Descripcio', models.TextField()),
                ('Quantitat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.TextField()),
                ('Descripcio', models.TextField()),
                ('Productes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.TextField()),
                ('Password', models.TextField()),
                ('CreditCard', models.IntegerField()),
            ],
        ),
    ]
