# Generated by Django 2.1.7 on 2019-02-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydrugstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.TextField()),
                ('Descripcio', models.TextField()),
                ('Photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.RenameField(
            model_name='usuari',
            old_name='ID',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cataleg',
            name='Descripcio_prod',
        ),
        migrations.RemoveField(
            model_name='cataleg',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='cataleg',
            name='ProducteId',
        ),
        migrations.RemoveField(
            model_name='estoc',
            name='Descripcio',
        ),
        migrations.RemoveField(
            model_name='estoc',
            name='ProducteId',
        ),
        migrations.AddField(
            model_name='carritodecompra',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mydrugstore.Usuari'),
        ),
        migrations.AddField(
            model_name='cataleg',
            name='Prize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cataleg',
            name='Producte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mydrugstore.Estoc'),
        ),
        migrations.AddField(
            model_name='cataleg',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carritodecompra',
            name='Prize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mydrugstore.Cataleg'),
        ),
        migrations.AlterField(
            model_name='estoc',
            name='Producte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mydrugstore.Producte'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Productes',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.DO_NOTHING, to='mydrugstore.Producte'),
        ),
    ]
